# -*- coding: utf-8 -*-
"""plot_new_baselines_color.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1up49jlVU5zMg9mqKuh3i6ARNgdGtfHbP
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Define color mapping with new style requirements
color_map = {
    'Chronos_with_NFCI': 'red',           # Solid red with marker (wider line)
    'Chronos_without_NFCI': 'black',      # Solid black with marker (thin line)
    'WEO': '#1F77B4',                     # Light blue, short dash, no marker
    'Truth': 'grey'                       # Grey, thin solid, no marker
}

# Country code to full name mapping
country_map = {
    'SGP': 'Singapore',
    'GBR': 'United Kingdom',
    'JPN': 'Japan',
    'DEU': 'Germany',
    'ITA': 'Italy',
    'FRA': 'France',
    'CAN': 'Canada',
    'CHN': 'China',
    'USA': 'United States'
}

# Output folder
output_dir = 'NGDP_PCH_plots'
os.makedirs(output_dir, exist_ok=True)

# Process each country
for country_code, country_name in country_map.items():
    file_path = f'figure_all_country0507_02/{country_code}/{country_code}_NGDP_PCH_pred_vs_true_compare.csv'

    if not os.path.isfile(file_path):
        print(f"File not found: {file_path}")
        continue

    df = pd.read_csv(file_path)
    df.set_index('Year', inplace=True)

    # Plotting
    plt.figure(figsize=(20, 10))

    plt.plot(df.index, df['Chronos_with_NFCI'], label='Chronos with NFCI',
             color=color_map['Chronos_with_NFCI'], linewidth=3, marker='o', markersize=7)

    plt.plot(df.index, df['Chronos_without_NFCI'], label='Chronos without NFCI',
             color=color_map['Chronos_without_NFCI'], linewidth=1.5, marker='o', markersize=7)

    plt.plot(df.index, df['WEO'], label='WEO',
             color=color_map['WEO'], linestyle=(0, (3, 2)), linewidth=1.5)

    plt.plot(df.index, df['Truth'], label='Ground Truth',
             color=color_map['Truth'], linestyle='solid', linewidth=1.5)

    plt.xticks(np.arange(min(df.index), max(df.index) + 1, step=2))
    plt.title(f"{country_name} - NGDP_PCH", fontsize=18)
    plt.xlabel("Year", fontsize=14)
    plt.ylabel("Value", fontsize=14)
    plt.legend(loc='lower right', fontsize=14)
    plt.grid(True)
    plt.tight_layout()

    # Save plot
    save_path = os.path.join(output_dir, f"{country_code}_NGDP_PCH_plot.png")
    plt.savefig(save_path)
    plt.close()

    print(f"Saved plot for {country_name} to {save_path}")

